### ISSUE TITLE
customlistviewrow file

### ISSUE THREAD

**Issue by elera** [jmpessoa/lazandroidmodulewizard#10]
Hi jmpessoa.

Laz_And_Controls file, row 1446, customlistviewrow unit is not present.

Thanks.

**Comment by jmpessoa** [comment]
Sorry, we need fix/remove its!   .... "customlistviewrow" is just  a test code.... I wil remove it now! Thank you!

**Comment by jmpessoa** [comment]
Ok, "customlistviewrow" was removed! Now I can present my findings with "customlistviewrow".  In fact, I investigated the possibility of the jCustomListViewRow as jCustomDialog paradigm... as suggested here   by elera/Fatih and I got some good [but only] partial results... Why? because I could insert only ONE line per template! So, if a have 100 line I will need 100 template... So my "solution" became impracticable... Now I need try other paradigm ... Well, that's the brief history of "customlistviewrow"....  :-(
